
spring:
  datasource:
    driverclassname: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/local
    username: root
    password: root
    platform: mysql
    hikari:
      maximum-pool-size: 10
  flyway:
    schemas: USER

server:
  port: 80

---
spring:
  profiles: container
  datasource:
    driverclassname: org.mariadb.jdbc.Driver
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    platform: mysql
    hikari:
      maximum-pool-size: 10
  flyway:
    schemas: USER
