version: "2.1"
services:
  dbStorage:
    image: busybox
  db:
    image: "mariadb:10.1"
    env_file:
      - "db.env"
    volumes_from:
      - dbStorage
#  front:
#    image: "michaelcoll/anim-enfance-front"
#    ports:
#      - "80:80"
  eureka:
    image: "michaelcoll/ae-eureka"
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
  indexer:
    image: "michaelcoll/ae-indexer"
    depends_on:
      - db
      - eureka
    links:
      - "eureka:eureka"
      - "db:db"
    env_file:
      - "db.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    image: "michaelcoll/ae-web"
    depends_on:
      - db
      - eureka
      - indexer
    links:
      - "eureka:eureka"
      - "db:db"
      - "indexer:indexer"
    ports:
      - 8080:8080
    env_file:
      - "db.env"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
