---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: anim-enfance
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: anim-enfance
    tier: database
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: anim-enfance
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anim-enfance
        tier: database
    spec:
      containers:
        - image: mariadb:10.1
          name: db
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: ae-db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ae-db-credentials
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ae-db-credentials
                  key: root-password
            - name: MYSQL_DATABASE
              value: ae-db

          ports:
            - containerPort: 3306
              name: db
