---
apiVersion: v1
kind: Service
metadata:
  name: creche-service
  labels:
    app: anim-enfance
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: anim-enfance
    tier: creche
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: creche-service
  labels:
    app: anim-enfance
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: anim-enfance
        tier: creche
    spec:
      containers:
        - image: michaelcoll/ae-creche-service
          imagePullPolicy: Always
          name: creche-service
          env:
            - name: MYSQL_DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: username
            - name: MYSQL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: password
            - name: MYSQL_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: host
            - name: MYSQL_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: demo-credentials
                  key: port
          ports:
            - containerPort: 80
              name: web
